Horrible hack to work around unknown brokeness. --- AttributeError: 'unicode' object has no attribute 'strftime' This error is caused by the default handler on the row
I have
  Column('time',     DateTime,    nullable=False, index=True,
   onupdate=func.current_timestamp(), default=func.current_timestamp()),

func.current_timestamp is returning a unicode string hence I get the above
error.